### ISSUE TITLE
Initial page modifications not visialized

### ISSUE THREAD

**Issue by IrisBC** [Milad-Akarie/smooth_page_indicator#1]
Hi!
I have been looking through your work and found out that on modifications of the initial page on the PageController, on the first visualization the dot is active at the first place anyway.
I am using this: _final pageCtrl = PageController(viewportFraction: 1.0, **initialPage: 1**);_
Together with the following indicator:
            _child: SmoothPageIndicator(
              controller: pageCtrl,
              count: 2,
              effect: ColorTransitionEffect(),
            ),_

So, the dot on 0 is marked but the page on 1 is displayed.
I found it a bit randomly and do not need it! But I though maybe you'd like to know :)
Thanks for developing!

**Comment by Milad-Akarie** [comment]
Hey @IrisBC, That's quite a nice observation!
Fixed in v0.1.3
Thanks for reporting.
