### ISSUE TITLE
Implement indicators with Axis.vertical scroll direction 

### ISSUE THREAD

**Issue by JHBitencourt** [Milad-Akarie/smooth_page_indicator#12]
Currently the package does not support using it with `PageView`'s `scrollDirection: Axis.vertical`.

Instead of rendering this:

![image](https://user-images.githubusercontent.com/9002831/83958347-ddc3df80-a846-11ea-8b60-48674e317bf9.png)

It should render in Y axis:

![image](https://user-images.githubusercontent.com/9002831/83958344-d6043b00-a846-11ea-9dfe-60801090419d.png)

Maybe a parameter `scrollDirection` must be implemented:

```dart
SmoothPageIndicator(
  controller: pageController,
  scrollDirection: Axis.vertical,
);
```

**Comment by Milad-Akarie** [comment]
@JHBitencourt Implemented in v0.2.0 check it out!
