### ISSUE TITLE
Enable applying a different colour for an indicator based on the index

### ISSUE THREAD

**Issue by dev-horacebg** [Milad-Akarie/smooth_page_indicator#13]
I'm using this as part of a wizard-like question form.
Once a user has successfully completed a section, or chosen to skip, we move on to the next screen. I'd like to be able to set the colour of the indicator to reflect the completed or skipped state.

Ideally, there'd be a way to specify the appearance of a dot at a given index, maybe via a builder.

**Comment by ChinHairSaintClair** [comment]
I too have this requirement.

**Comment by Milad-Akarie** [comment]
@dev-horacebg @ChinHairSaintClair  use  the new CustomizableEffect
