### ISSUE TITLE
Page transition Programmatically

### ISSUE THREAD

**Issue by theabhishekavi** [Milad-Akarie/smooth_page_indicator#16]
How can we move from one page to another on click of a button rather than swiping

**Comment by Milad-Akarie** [comment]
@theabhishekavi This is not related to smooth_page_indicator but you can achieve that using
`pageController.animateToPage(pageNumber,duration:..,curve:..)`
or 
`pageController.jumpTopage(pageNumber)` if you wanna skip animation
