### ISSUE TITLE
How do you add this to my yaml as a dependency?

### ISSUE THREAD

**Issue by mrgithub** [Milad-Akarie/smooth_page_indicator#2]

**Comment by lordvidex** [comment]
@mrgithub this is the pub.dev documentation:: https://pub.dev/packages/smooth_page_indicator and you can check how to install it here: https://pub.dev/packages/smooth_page_indicator#-installing-tab-

**Comment by Milad-Akarie** [comment]
@mrgithub  add this to your dependencies
smooth_page_indicator: ^0.1.3
