### ISSUE TITLE
Scale effect with border shape

### ISSUE THREAD

**Issue by fauziloyalto** [Milad-Akarie/smooth_page_indicator#20]
I read all the documentation, but I couldn't find any way to get this look.
<img width="176" alt="Screen Shot 2020-09-25 at 15 52 23" src="https://user-images.githubusercontent.com/68621545/94247580-86599480-ff47-11ea-886e-e9f156069b74.png">
can anyone help me with that?

**Comment by nilsi** [comment]
I just created a similar issue.

Let me know if you figure it out.

https://github.com/Milad-Akarie/smooth_page_indicator/issues/19

**Comment by Milad-Akarie** [comment]
Try this
activePaintingStyle: PaintingStyle.stroke
