### ISSUE TITLE
Getting this error when last item was removed

### ISSUE THREAD

**Issue by TBoonkwan** [Milad-Akarie/smooth_page_indicator#21]
Current page is out of bounds
'package:smooth_page_indicator/src/painters/indicator_painter.dart':
Failed assertion: line 26 pos 16: 'offset.ceil() < count'

**Comment by Milad-Akarie** [comment]
You need rebuild your new state after removing the or adding new pages

**Comment by MirceaX2Mobile** [comment]
@Milad-Akarie I'm having the same trouble, after I remove the last item I'm calling setState but the error is still showing.

```
SmoothPageIndicator(
                    controller: _controller,
                    count: _myPlaces.length,
                    effect: WormEffect(activeDotColor: primaryBlack),
                    onDotClicked: (index) {
                      moveController(index);
                    }
                ),
```
`
setState(() {
                    _myPlaces.removeAt(_index);
                  });`

And these are the properties of the State:
```
class _MyHomePageState extends State<MyHomePage> {
  int _index = 0;
  List<Place> _myPlaces = [];
  PageController _controller = PageController(viewportFraction: 1);
```

**Comment by moiye-dev** [comment]
I am also experiencing this exception when I delete the last item. Any Ideas?

**Comment by callmejm** [comment]
I also having this issue when remove the last item

**Comment by callmejm** [comment]
I found a solution for this, `count` cannot be `0`, so need to put a condition if the length is 0 , return as `1` should be fine

**Comment by PcolBP** [comment]
You have to move page as well when deleting element.
I have someting as this in my app 
```
void _itemDeletionEvaluator(String magKey) {
    //Checks if PageController isn't null and has clients
    if (_isPageControllerValid) {
      //If actualPAge isn't start and last one so theres no needs for move page
      if (_actualPage > 0 && _actualPage == magazinesLength - 1) {
        //If filter is all or current magazine is current filter so user can se change than animate change
        if (_filter == FavoriteFilter.all ||
            _filter == _getFilterOfMagazine(magKey)) {
          _pageController!.jumpToPage(_actualPage - 1);
        }
      }
    }
  }
```

**Comment by zanpen2000** [comment]
我也遇到了同样的问题，有没有解决办法？

**Comment by callmejm** [comment]
> 我也遇到了同样的问题，有没有解决办法？

可以尝试我的方法
https://github.com/Milad-Akarie/smooth_page_indicator/issues/21#issuecomment-846424555

**Comment by zanpen2000** [comment]
> > 我也遇到了同样的问题，有没有解决办法？
> 
> 可以尝试我的方法
> [#21 (comment)](https://github.com/Milad-Akarie/smooth_page_indicator/issues/21#issuecomment-846424555)

我的情况和你的还不太一样，我是删除数组（共5个）最后一个元素时报错，我一直以为可能是 activeIndex超出 list.length了，下断点查看发现不是。

这个问题是绘制Worm的时候出现的（这个我控制不了）

ps： 我用的是`AnimatedSmoothIndicator`， 现在换到了`SmoothPageIndicator`正常了，希望作者尽快把这个问题解决吧 

![image](https://user-images.githubusercontent.com/3360804/129673854-3f79fdbf-d5e6-43e7-a31d-91b68851fe82.png)

**Comment by BanderMansour** [comment]
The Simplest way is to add condition on activeIndex if you reatch the last index jumb again to index 0
AnimatedSmoothIndicator(
                      activeIndex: liquidController.currentPage == 4
                          ? 0
                          : liquidController.currentPage,
                      count: 4,
                      effect: const WormEffect(
                          spacing: 14,
                          dotColor: Colors.white54,
                          activeDotColor: Colors.white),
                      onDotClicked: (index) {
                        liquidController.animateToPage(page: index);
                      }),
