### ISSUE TITLE
Can I adjust the size of the dot?

### ISSUE THREAD

**Issue by chounry** [Milad-Akarie/smooth_page_indicator#26]

**Comment by Milad-Akarie** [comment]
Yes
dotHeight:
dotWidth:

**Comment by JihyeJung-Work** [comment]
@Milad-Akarie Where can I change dotHeight and dotWidth? Could you give me an example?

**Comment by Milad-Akarie** [comment]
Inside of effect objects
`effect: WormEffect(dotHeight)`
