### ISSUE TITLE
Active Dot Width

### ISSUE THREAD

**Issue by Prn-Ice** [Milad-Akarie/smooth_page_indicator#27]
Hi, could you make it possible to change the active dot width?

**Comment by ShadyZekry** [comment]
You can use `activeDotScale`

**Comment by Milad-Akarie** [comment]
@Prn-Ice  use the new Customizable effect

**Comment by Hemang-Sidapara** [comment]
same issue for me, i want to change activeDotWidth in SwapEffect. any solution for it please ping me.
