### ISSUE TITLE
Error activeDotColor in ExpandingDotsEffect

### ISSUE THREAD

**Issue by erfanhemmati** [Milad-Akarie/smooth_page_indicator#3]
Hey my friend we can change activeDotColor in ExpandingDotsEffect ?!
@Milad-Akarie

**Comment by Milad-Akarie** [comment]
@erfanhemmati not in the current version you can't. Do you think it's needed?

**Comment by erfanhemmati** [comment]
Yes. We desperately need it in our projects.
@Milad-Akarie

**Comment by Milad-Akarie** [comment]
@erfanhemmati implemented in v0.1.4 with smooth transition enjoy!

**Comment by vladbalan** [comment]
Hey @erfanhemmati . I'm trying to change the `activeDotColor` to green, but I'm getting an error:
```dart
              SmoothPageIndicator(
                controller: controller,
                count: 6,
                effect: WormEffect(),
	        activeDotColor:  Colors.green,
              )
```
```
The named parameter 'activeDotColor' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'activeDotColor'.
```

Any idea what I'm doing wrong?

**Comment by erfanhemmati** [comment]
Hey @vladbalan 
you must be add activeDotColor property into WormEffect()
like this
`
                            effect: WormEffect(
                              activeDotColor: Colors.green
                            ),
`

**Comment by vladbalan** [comment]
@erfanhemmati Wow, I totally missed that! Thank you! 🥇

**Comment by erfanhemmati** [comment]
@vladbalan you're welcome :)
