### ISSUE TITLE
use related text instead of dot

### ISSUE THREAD

**Issue by AliEasy** [Milad-Akarie/smooth_page_indicator#30]
What I need is to use some related texts instead of dots (Like a title for each page as a text List) and by changing the page, instead of dots getting changed, the text gets to change

Or if there is any solution out side this package please let me know

sample video
![Screen_Recording_20201225-172749](https://user-images.githubusercontent.com/45623453/103136681-a2e8a280-46d7-11eb-960c-4222fa5cd713.gif)

**Comment by Edvardunsvag** [comment]
This would be extremely helpful. To be able to display the page number inside the dot for instance :)
