### ISSUE TITLE
It doesn't support scrolling

### ISSUE THREAD

**Issue by MirceaX2Mobile** [Milad-Akarie/smooth_page_indicator#31]
It doesn't support scrolling if the width is bigger than the screen. Hope you can fix this in the future.

**Comment by Milad-Akarie** [comment]
@MirceaX2Mobile use the scrolling dot effect for big number of pages
https://raw.githubusercontent.com/Milad-Akarie/smooth_page_indicator/master/demo/smooth_page_indicator_demo_4.gif

**Comment by MirceaX2Mobile** [comment]
@Milad-Akarie oh, thank you!
