### ISSUE TITLE
Add loop

### ISSUE THREAD

**Issue by maksimivanchuk** [Milad-Akarie/smooth_page_indicator#33]
Please, add loop for SmoothPageIndicator. 
I can make loop in scroll page view, like that
PageView.builder(
                __controller: pageController,
               __ onPageChanged: (int page) {},
                itemBuilder: (context, index) {
                  return _children[index % _children.length];
                },
           ),
but for SmoothPageIndicator is not available .

**Comment by codenashwan** [comment]
any solution ?

**Comment by Milad-Akarie** [comment]
@maksimivanchuk @codenashwan  done in v 1.0.0

**Comment by alejandrocoding** [comment]
Hi @Milad-Akarie and thanks for this lib.

Quick question, is there any way to disable the loop? I just want to get to the latest and not be able to rotate or move to first.

Thanks,

**Comment by hugoviktor** [comment]
to disable the loop remove  the property itemCount of the pageview.
