### ISSUE TITLE
ScrollEffect: active dot is not aligned with underlying dot

### ISSUE THREAD

**Issue by Kal-Elx** [Milad-Akarie/smooth_page_indicator#35]
The active dot misses the underlying dot with approximately 1 pixel when I use ScrollEffect. This does not occur for other effects afaik. 

![image](https://user-images.githubusercontent.com/41339152/109409867-77638c00-7996-11eb-9371-21d7f846f142.png)

Thanks for a great package!

**Comment by Milad-Akarie** [comment]
@kal Fixed in version 0.2.1 and 0.3.0-nullSafety.
Thanks for reporting.
