### ISSUE TITLE
Add support for ValueNotifier

### ISSUE THREAD

**Issue by fly-qp** [Milad-Akarie/smooth_page_indicator#53]
It would be very pleasing if we can see a support for ValueNotifier since we may use this not only with PageView. For example i am using a CarouselSlider and therefore it would be nice to have this feature :)

**Comment by Milad-Akarie** [comment]
Have you tried AnimatedSmoothİndicator?

`AnimatedSmoothIndicator(  
   activeIndex: yourActiveIndex,  
   count:  6,  
   effect:  WormEffect(),  
)`
