### ISSUE TITLE
Required horizontal scroll for ExpandingDotsEffect 

### ISSUE THREAD

**Issue by pravin-sorigin** [Milad-Akarie/smooth_page_indicator#54]
Required horizontal scroll for ExpandingDotsEffect when no. of dots goes beyond screen.
It works well when there are few pages. But no of pages are big then it sense like there is no indication for current page.

**Comment by Milad-Akarie** [comment]
Horizonal scroll is available for all effects

**Comment by pravin-sorigin** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/100113424/172308020-0adc1007-668d-4d7f-ba24-25e50c978e87.png">

@Milad-Akarie You can see above image. Indicator goan overflowed out of screen horizontally but indicator is not scrolled automatically.

I've used indicator like this,
```
AnimatedSmoothIndicator(
                activeIndex: _carouselIndicatorIndex,
                count: widget.items.length,
                axisDirection: Axis.horizontal,
                effect: const ExpandingDotsEffect(
                  dotWidth: 5,
                  dotHeight: 5,
                  activeDotColor: AppColors.appColor0xffffb64c,
                ),
              )
```

Please let me know If I'm doing anything wrong?

**Comment by Milad-Akarie** [comment]
@pravin-sorigin  I thought you were talking about direction, unfortunately, horizontal scroll is only supported by scrolling dots effect.
