### ISSUE TITLE
AnimatedSmoothIndicator does not work

### ISSUE THREAD

**Issue by elmar001** [Milad-Akarie/smooth_page_indicator#56]
AnimatedSmoothIndicator( activeIndex: yourActiveIndex, count: 6, effect: WormEffect(), ) does not work. It does not animate it.

**Comment by Milad-Akarie** [comment]
@elmar001 are you calling setState when your active index changes?

**Comment by elmar001** [comment]
No, I supposed it should animate itself so activeIndex is always same. Because documentation states like this:

Unlike SmoothPageIndicator, AnimatedSmoothIndicator is self animated and all it needs is the active index.

AnimatedSmoothIndicator(  
   activeIndex: yourActiveIndex,  
   count:  6,  
   effect:  WormEffect(),  
)  

Should I update activeIndex value periodically in order get it work?
