### ISSUE TITLE
SmoothPageIndicator work with CarouselSlider

### ISSUE THREAD

**Issue by peterbullmatti** [Milad-Akarie/smooth_page_indicator#59]
before SmoothPageIndicator works fine with CarouselSlider since it just needs an activeIndex, but the current version of SmoothPageIndicator need a Pagecontroller, and what I have is a CarouselController, how could I transfer this CarouselController to a pagecontroller?

    SmoothPageIndicator(
                  controller: _pageController // here I only have a CarouselController
                  count: controller.photoFrameList.length + 1,
                  effect: WormEffect(
                    activeDotColor: AppColors.sadColor,
                    dotColor: AppColors.sadColor.withOpacity(0.4),
                    dotHeight: 8,
                    dotWidth: 8,
                    type: WormType.thin,
                    // strokeWidth: 5,
                  ),
                ),
            

thank you!

**Comment by xjc5205** [comment]
Use a transparent pageView as the middleware. The pageView follows CarouselSlider, and the SmoothPageIndicator follows the pageView

**Comment by fly-qp** [comment]
Use ValueNotifier<int> in combination with ValueListenableBuilder.
In CarouselSlider just implement onPageChanged like this:

`onPageChanged: (int index, reason) => _valueNotifier.value = index`

And then you can just use AnimatedSmoothIndicator with activeIndex property like this:

```
ValueListenableBuilder<int>(
  valueListenable: _valueNotifier,
  builder: (BuildContext context, int index, Widget? child) =>
      AnimatedSmoothIndicator(
            activeIndex: index,
            axisDirection: Axis.horizontal,
            count: images.length,
            onDotClicked: _carouselController.animateToPage))
```

**Comment by Hemang-Sidapara** [comment]
use AnimatedSmoothIndicator instead of SmoothPageIndicator, there no need of any controller just need to pass activeIndex
