### ISSUE TITLE
Different look for active dot

### ISSUE THREAD

**Issue by MatsAndT** [Milad-Akarie/smooth_page_indicator#6]
Is it a way to have the active dot look different than the other dots? like this:
![image](https://user-images.githubusercontent.com/23106882/79164041-7ce8cf80-7de0-11ea-88d1-39067c33bcae.png)
or
![image](https://user-images.githubusercontent.com/23106882/79164053-870ace00-7de0-11ea-849f-b25836f1bc46.png)

If this is not implemented, can it be added?

**Comment by MatsAndT** [comment]
like activeDotWidth, activeDotHeight, activeDotPaintStyle

**Comment by Milad-Akarie** [comment]
@MatsAndT did you try the scale effect?

```dart
           effect: ScaleEffect(
              scale: 1.5,
              activeDotColor: Colors.black,
         ),
```

**Comment by MatsAndT** [comment]
no, I did not, did use color transition. Thenk you.
