### ISSUE TITLE
Wrong margin in AnimatedSmoothIndicator with ScaleEffect

### ISSUE THREAD

**Issue by TheManuz** [Milad-Akarie/smooth_page_indicator#61]
`AnimatedSmoothIndicator` with `ScaleEffect` has an additional margin on the right size, which **causes a slight offset** when wrapping the indicator in a `Center` widget.

These are the settings I'm using:

```dart
AnimatedSmoothIndicator(
    activeIndex: index,
    count: count,
    effect: ScaleEffect(
        activeDotColor: colorScheme.primary,
        dotColor: colorScheme.primaryContainer,
        spacing: 8,
        dotWidth: 8,
        dotHeight: 8,
    ),
),
```

This is the result with `Show guidelines` enabled:
![scale_effect_margin](https://user-images.githubusercontent.com/2032334/204784598-6d51e9b0-b68f-41ff-8969-8d8d833ee3f5.jpg)

The margin on the right shouldn't be there.

**Comment by Milad-Akarie** [comment]
@TheManuz Fixed in new version
