### ISSUE TITLE
Can you please make the indicator buttons be able to change pages?

### ISSUE THREAD

**Issue by imrnh2002** [Milad-Akarie/smooth_page_indicator#66]
Can you please make the indicator buttons be able to change pages? I think I really need them. I was trying to make a page, where carousel images are in the bottom layer and buttons are in the upper layer of a stack.  
![image](https://user-images.githubusercontent.com/127003890/235323288-cd263c6d-d31d-4925-aef2-261a1a119326.png)
It seems not a feasible idea to do so. At least because these buttons are useless in a way that they just indicates and can't co-operate

I checked the **onDotClicked** function. Is there any way you can suggest me how to update the UI inside PageView.builder using this function and index found on it?

**Comment by imrnh2002** [comment]
Solved it.

**Comment by mattheuhtn** [comment]
How to do  that -.-

**Comment by imrnh2002** [comment]
You solved it?
