### ISSUE TITLE
How can I get the result of WormEffect and ExpandingDotsEffect together?

### ISSUE THREAD

**Issue by bernabedev** [Milad-Akarie/smooth_page_indicator#68]
Hello,

I'm currently using your library and I find it incredibly useful. Thanks for your hard work on this project!

I have a specific use-case where I'd like to combine both **WormEffect** and ExpandingDotsEffect into a single experience for my users. Is there a straightforward way to achieve this within the current framework of your library? Or would you recommend a custom implementation to get both effects working together?

Thank you for your time and any guidance you can provide.

Best regards,
Freilyn Bernabe

**Comment by Milad-Akarie** [comment]
@Freilynbp03 that seems a bit hard to implement, do you have a visual e.g of your requirement?

**Comment by bernabedev** [comment]
indicator.gif
<https://mail.google.com/mail/u/0?ui=2&ik=ae9db4385a&attid=0.1&permmsgid=msg-a:r3938045184209635511&view=att&disp=safe&realattid=f_lm99xxsn0>
(1,018 K)

<https://mail.google.com/mail/u/0?ui=2&ik=ae9db4385a&attid=0.1&permmsgid=msg-a:r3938045184209635511&view=att&disp=safe&realattid=f_lm99xxsn0>First
of all, I apologize for the delay in responding to your query. Thank you
for your patience.

In response to your question about having a visual example to better
understand the requirement, I'm glad to say, yes, we do have an example to
share. Attached to this email, you'll find a mock-up that outlines the key
features and the intended user experience. I believe this visual guide will
provide a clearer perspective on what we're aiming to achieve.

Please take a look and let me know if this clarifies your concerns or if
you have any more questions.

Best regards:

Freilyn Bernabe
