### ISSUE TITLE
Performance Issue: SmoothPageIndicator is being rebuild very often =>janking

### ISSUE THREAD

**Issue by theemaster** [Milad-Akarie/smooth_page_indicator#7]
The SmoothPageIndicator widget is being rebuild several times which leads to janking while switching between different pages. It is even noticeable in the release version of the app.

`                child: SmoothPageIndicator(
                  controller: controller,
                  count: cards.length,
                  effect: ExpandingDotsEffect(
                    activeDotColor: kOnSelected,
                    dotColor: kBackgroundColorSecondary,
                    expansionFactor: 3,
                  ),
                )`

**Comment by Milad-Akarie** [comment]
@theemaster SmoothPageIndicator is an animated widget, it rebuilds every time the controller emits a new value. how does your complete setup look like?
