### ISSUE TITLE
Add possibility to provide border for Swap active item

### ISSUE THREAD

**Issue by VasylRolique** [Milad-Akarie/smooth_page_indicator#71]
It would be nice if you add a possibility to add a border for active items, in this case, I would have the possibility to use this library on my project. I attach an example of what I expected that could be possible to implement in the end.
<img width="305" alt="image" src="https://github.com/Milad-Akarie/smooth_page_indicator/assets/70259157/b81975f7-293e-4c7d-98d9-838151d39627">

**Comment by FlawLessx** [comment]
did you find solution?
