### ISSUE TITLE
Active dot not preserving state

### ISSUE THREAD

**Issue by neofactoris3** [Milad-Akarie/smooth_page_indicator#8]
When moved to a different tab and returned, the active dot moves to the first position but on scroll change, it moves to the correct position. How to ensure that the active dot state is preserved when moving to different tabs etc?

**Comment by Milad-Akarie** [comment]
@neofactoris3 can you please share your setup so I can reproduce this?

**Comment by neofactoris3** [comment]
`
ListView home() {
    return ListView(
      padding: const EdgeInsets.all(0.0),
      key: PageStorageKey('HomeKey'),
      children: <Widget>[
        SafeArea(
          child: new Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              new Container(
                height: 300.0,
                child: Container(
                  child: SingleChildScrollView(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        SizedBox(
                          /*height: MediaQuery.of(context).size.height /10,*/
                          height: 10.0,
                        ),
                        Image(
                          image: AssetImage("images/tng"),
                        ),
                        SizedBox(
                          /*height: MediaQuery.of(context).size.height /10,*/
                          height: 5.0,
                        ),
                        Text(
                          "Gggh",
                          style: TextStyle(
                              color: Colors.black54.withOpacity(0.3),
                              fontSize: 18.0,
                              fontWeight: FontWeight.bold),
                        ),
                        SizedBox(
                          height: 5.0,
                        ),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: <Widget>[
                            Text(
                              "G ",
                              style: TextStyle(
                                  fontSize: 26.0,
                                  color: Color(0xFF323643),
                                  fontWeight: FontWeight.bold),
                            ),
                            Text(
                              "Gg",
                              style: TextStyle(
                                  fontSize: 26.0,
                                  foreground: Paint()..shader = linearGradient,
                                  fontWeight: FontWeight.bold),
                            )
                          ],
                        ),

/*
                        SizedBox(
                          height: 20.0,
                        ),
                        Center(
                          child: Column(
                            children: <Widget>[
                              Text(
                                "Copyright © 2020",
                                style:
                                    TextStyle(color: Color(0xFF9DA3B4), fontSize: 12),
                              ),
                              Text(
                                "Created and Main",
                                style:
                                TextStyle(color: Color(0xFF9DA3B4), fontSize: 12),
                              )
                            ],
                          ),
                        )*/
                      ],
                    ),
                  ),
                ),
              ),
              new Container(
                margin: const EdgeInsets.only(left: 20.0, right: 20.0),
                height: 250.0,
                width: MediaQuery.of(context).size.width - 40,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Row(
                      children: <Widget>[
                        Expanded(
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: <Widget>[
                              Container(
                                /*   margin: EdgeInsets.only(left: 10),*/
                                padding: EdgeInsets.symmetric(
                                    horizontal: 10.0, vertical: 5.0),
                                color: Color(0xff449e47),
                                child: Text(
                                  'Latest News',
                                  style: TextStyle(
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                              Container(
                                /*   margin: EdgeInsets.only(right: 10.0),*/
                                padding: EdgeInsets.symmetric(
                                    horizontal: 10.0, vertical: 5.0),
                                child: InkWell(
                                  onTap: () {},
                                  child: Text(
                                    'View All',
                                    style: TextStyle(
                                      fontSize: 15,
                                      color: Color(0xff449e47),
                                      fontWeight: FontWeight.w600,
                                      fontFamily: 'GoogleMedium',
                                      /*color: Colors.black54*/
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        new SizedBox(
                          height: 32.0,
                        ),
                      ],
                    ),
                    new Expanded(
                        child: Container(
                      /*decoration: BoxDecoration(
                              gradient: LinearGradient(
                                  begin: Alignment.topRight,
                                  end: Alignment.bottomLeft,
                                  colors: [Colors.grey.withOpacity(0.5), Colors.white70])),*/
                      child: new StreamBuilder<DocumentSnapshot>(
                        stream: Firestore.instance
                            .collection('Users')
                            .document(userId)
                            .snapshots(),
                        builder: (BuildContext context,
                            AsyncSnapshot<DocumentSnapshot> snapshot) {
                          if (!snapshot.hasData) {
                            return Center(
                                child: SpinKitThreeBounce(
                              size: 24.0,
                              itemBuilder: (_, index) {
                                return DecoratedBox(
                                  decoration: BoxDecoration(
                                      gradient: blueGreenGradient,
                                      shape: BoxShape.circle),
                                );
                              },
                            ));
                          }

                          if (snapshot.hasError)
                            return Center(
                                child: new Text('Error: ${snapshot.error}'));

                          switch (snapshot.connectionState) {
                            case ConnectionState.none:
                              return new Center(
                                child: Text("Connection Not Found"),
                              );
                            case ConnectionState.waiting:
                              return Center(
                                  child: SpinKitThreeBounce(
                                size: 24.0,
                                itemBuilder: (_, index) {
                                  return DecoratedBox(
                                    decoration: BoxDecoration(
                                        gradient: blueGreenGradient,
                                        shape: BoxShape.circle),
                                  );
                                },
                              ));

                            default:
                              if (snapshot.data['unreadNews'].toList().length >
                                  0) {
                                return Column(
                                  children: <Widget>[
                                    Expanded(
                                      child: new PageView.builder(
                                        key: new PageStorageKey('keying'),
                                        controller: _controller,
                                        physics: BouncingScrollPhysics(),
                                        itemCount: snapshot.data['unreadNews']
                                            .toList()
                                            .length,
                                        itemBuilder:
                                            (BuildContext context, int index) {
                                          /* String newsId = snapshot.data['unreadNews']
                                              .toList()[index];*/
                                          return new StreamBuilder<
                                                  DocumentSnapshot>(
                                              stream: Firestore.instance
                                                  .collection('news')
                                                  .document(snapshot
                                                      .data['unreadNews']
                                                      .toList()[index]
                                                      .toString())
                                                  .snapshots(),
                                              builder: (BuildContext context,
                                                  AsyncSnapshot<
                                                          DocumentSnapshot>
                                                      newsDocumentSnapshot) {
                                                switch (newsDocumentSnapshot
                                                    .connectionState) {
                                                  case ConnectionState.none:
                                                    return new Center(
                                                      child: Text(
                                                          "Connection Not Found"),
                                                    );
                                                  case ConnectionState.waiting:
                                                    return Center(
                                                        child:
                                                            SpinKitThreeBounce(
                                                      size: 24.0,
                                                      itemBuilder: (_, index) {
                                                        return DecoratedBox(
                                                          decoration: BoxDecoration(
                                                              gradient:
                                                                  blackBlueGradient,
                                                              shape: BoxShape
                                                                  .circle),
                                                        );
                                                      },
                                                    ));

                                                  default:
                                                    /*return NewsCell(document);*/

                                                    return Column(
                                                      children: <Widget>[
                                                        GestureDetector(
                                                          child: Container(
                                                            padding:
                                                                const EdgeInsets
                                                                    .all(8.0),
                                                            child: new Card(
                                                              shape:
                                                                  RoundedRectangleBorder(
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            20.0),
                                                              ),
                                                              elevation: 5.0,
                                                              color: Color(
                                                                  0xFFFAFBFD),
                                                              child:
                                                                  new Padding(
                                                                padding:
                                                                    new EdgeInsets
                                                                            .all(
                                                                        16.0),
                                                                child:
                                                                    new Column(
                                                                  children: [
                                                                    new Row(
                                                                        children: <
                                                                            Widget>[
                                                                          Flexible(
                                                                            child:
                                                                                Padding(
                                                                              padding: new EdgeInsets.only(left: 4.0),
                                                                              child: new Container(
                                                                                child: new Text(
                                                                                  newsDocumentSnapshot.data['title'],
                                                                                  overflow: TextOverflow.ellipsis,
                                                                                  maxLines: 1,
                                                                                  style: TextStyle(
                                                                                    fontSize: 18,
                                                                                    color: Color(0xFF6aa06e),
                                                                                    fontWeight: FontWeight.bold,
                                                                                  ),
                                                                                ),
                                                                              ),
                                                                            ),
                                                                          ),
                                                                        ]),
                                                                    new Row(
                                                                      children: [
                                                                        new Expanded(
                                                                          child:
                                                                              new Column(
                                                                            crossAxisAlignment:
                                                                                CrossAxisAlignment.start,
                                                                            children: [
                                                                              Padding(
                                                                                padding: new EdgeInsets.only(
                                                                                  top: 1.0,
                                                                                  right: 8.0,
                                                                                  bottom: 10.0,
                                                                                ),
                                                                                child: Row(
                                                                                  children: <Widget>[
                                                                                    new Padding(
                                                                                      padding: new EdgeInsets.only(left: 4.0),
                                                                                      child: Container(
                                                                                        child: new Text(
                                                                                          timeago.format(newsDocumentSnapshot.data['publishedAt'].toDate()) + ' by',
                                                                                          overflow: TextOverflow.ellipsis,
                                                                                          maxLines: 1,
                                                                                          style: new TextStyle(
                                                                                            fontWeight: FontWeight.w400,
                                                                                            //color: Color(0xFF6aa06e),
                                                                                            color: Colors.black54,
                                                                                          ),
                                                                                        ),
                                                                                      ),
                                                                                    ),
                                                                                    new Padding(
                                                                                      padding: new EdgeInsets.all(5.0),
                                                                                      child: new Text(
                                                                                        newsDocumentSnapshot.data['author'],
                                                                                        style: new TextStyle(
                                                                                            fontWeight: FontWeight.w500,
                                                                                            //color: Color(0xFF6aa06e),
                                                                                            color: Colors.black54),
                                                                                      ),
                                                                                    ),
                                                                                  ],
                                                                                ),
                                                                              ),
                                                                              new Padding(
                                                                                padding: new EdgeInsets.only(left: 4.0, right: 4.0, bottom: 4.0),
                                                                                child: Container(
                                                                                  child: new Text(
                                                                                    newsDocumentSnapshot.data['shortDesc'],
                                                                                    maxLines: 5,
                                                                                    overflow: TextOverflow.ellipsis,
                                                                                    style: TextStyle(
                                                                                        fontWeight: FontWeight.w500,
                                                                                        //color: Color(0xFF6aa06e),
                                                                                        color: Colors.black54),
                                                                                  ),
                                                                                ),
                                                                              ),
                                                                            ],
                                                                          ),
                                                                        ),
                                                                      ],
                                                                    )
                                                                  ],
                                                                ), ////
                                                              ),
                                                            ),
                                                          ),
                                                          onTap: () {
                                                            DocumentReference
                                                                referencee =
                                                                Firestore
                                                                    .instance
                                                                    .collection(
                                                                        'Users')
                                                                    .document(
                                                                        user.uid);

                                                            Navigator.push(
                                                                context,
                                                                MaterialPageRoute(
                                                                    builder:
                                                                        (context) {
                                                              return NewsDetails(
                                                                  newsDocumentSnapshot
                                                                      .data);
                                                            }));

                                                            referencee
                                                                .updateData({
                                                              'unreadNews':
                                                                  FieldValue
                                                                      .arrayRemove([
                                                                newsDocumentSnapshot
                                                                    .data
                                                                    .documentID
                                                              ])
                                                            });
                                                          },
                                                        ),
                                                      ],
                                                    );
                                                }
                                              });
                                        },
                                      ),
                                    ),
                                    Container(
                                      width: MediaQuery.of(context).size.width -
                                          40,
                                      child: Center(
                                        child: new SmoothPageIndicator(
                                          controller: _controller,
                                          // PageController
                                          count: snapshot.data['unreadNews']
                                              .toList()
                                              .length,
                                          effect: SlideEffect(
                                              spacing: 4.0,
                                              radius: 4.0,
                                              dotWidth: 12.0,
                                              dotHeight: 6.0,
                                              paintStyle: PaintingStyle.fill,
                                              /*strokeWidth: 1.5,*/
                                              dotColor:
                                                  Colors.grey.withOpacity(0.5),
                                              activeDotColor: Color(
                                                  0xff449e47)), // your preferred effect
                                        ),
                                      ),
                                    )
                                  ],
                                );
                              }
                              return Padding(
                                padding: const EdgeInsets.all(50.0),
                                child: Container(
                                  height: 250.0,
                                  width: MediaQuery.of(context).size.width,
                                  decoration: BoxDecoration(
                                      image: new DecorationImage(
                                          colorFilter: new ColorFilter.mode(
                                              Colors.black.withOpacity(0.5),
                                              BlendMode.dstOut),
                                          image: new AssetImage(
                                              'images/empty.png'),
                                          fit: BoxFit.cover),
                                      shape: BoxShape.circle),
                                ),
                              );
                          }
                        },
                      ),
                    )),
                  ],
                ),
              ),
              /* new SizedBox(
                  height: 24.0,
                ),*/
            ],
          ),
        )
      ],
    );
  }



`

**Comment by neofactoris3** [comment]
[https://pastebin.com/HbeFft8g](url)

**Comment by Milad-Akarie** [comment]
@neofactoris3 I think your link is broken?

**Comment by neofactoris3** [comment]
https://pastebin.com/HbeFft8g

**Comment by Milad-Akarie** [comment]
Where are you initializing your PageController?

**Comment by neofactoris3** [comment]
`class _GetAppState extends State<GetApp> {`
`PageController _controller = PageController(initialPage: 0);` 
` }`

**Comment by neofactoris3** [comment]
Any updates?

**Comment by neofactoris3** [comment]
I have tried to set a key as well but it does no work...

`new SmoothPageIndicator(
                                           key: PageStorageKey('smoothPageIndicatorKey'),
                                            controller: _controller, count: snapshot.data['unreadNews']
                                                .toList()
                                                .length, 
                                            effect: SlideEffect(
                                                spacing: 4.0,
                                                radius: 4.0,
                                                dotWidth: 12.0,
                                                dotHeight: 6.0,
                                                paintStyle: PaintingStyle.fill,
                                                dotColor: Colors.grey
                                                    .withOpacity(0.3),
                                                activeDotColor: Color(
                                                    0xff449e47)),
                                          ), `

Any help is much appreciated...


Thank you!

**Comment by Milad-Akarie** [comment]
@neofactoris3 Sorry for keeping you waiting, I was actually really busy lately. 
I'll look into it today.

you're using TabView to handle your tabs right?

**Comment by Milad-Akarie** [comment]
@neofactoris3 I failed to reproduce the error. could you create a gist of a working example?

**Comment by Milad-Akarie** [comment]
@neofactoris3  This might help
https://github.com/Milad-Akarie/auto_route_library/issues/81#issuecomment-620580590

**Comment by neofactoris3** [comment]
I had tried it earlier... It was not working...


In fact, the page viewer does not lose the state, when I navigate back to the parent page, I can see the pageviewer retains the page I left it but smooth_page_indicator active dot is at the first position, however, if I slide the page, the active dot goes back to the exact location.

**Comment by Milad-Akarie** [comment]
smooth_page_indicator is sharing the same state with the pageView so this's really confusing lol

**Comment by neofactoris3** [comment]
This is what happens

**Comment by neofactoris3** [comment]
Added video

**Comment by neofactoris3** [comment]
This is what happens...
[Video demonstration](https://photos.app.goo.gl/FxBk2b1kshbvmYXD8)

**Comment by Milad-Akarie** [comment]
@neofactoris3 I see.. What are you using to manage your tabs? TabView?

**Comment by neofactoris3** [comment]
it's [fancy bottom navigation](https://pub.dev/packages/fancy_bottom_navigation)

**Comment by Walker-ZHAO** [comment]
@neofactoris3 you can use FutureBuilder to wrap SmoothPageIndicator. Ref: https://stackoverflow.com/questions/61058420/flutter-pagecontroller-page-cannot-be-accessed-before-a-pageview-is-built-with
