### ISSUE TITLE
What will hapeend if my count more then 50 and more - can adjust left and right side padding or margin for  AnimatedSmoothIndicator widgets ?

### ISSUE THREAD

**Issue by anilthummar** [Milad-Akarie/smooth_page_indicator#80]
@Milad-Akarie ,

What will hapeend if my count more then 50 and more , it will be set proper UI in widgets in both side - left and right ?
below is my code Please suggest me how to fixed right side alignment issue.

**`Widget dotIndicator() => Row(
    mainAxisAlignment: MainAxisAlignment.center, // Align dots at the ends
    children: [
      Flexible( // Use Flexible to prevent overflow
        child: AnimatedSmoothIndicator(
          activeIndex: currentIndex,
          count: widget.userBannersList!.length,
          effect: const ExpandingDotsEffect(
            dotHeight: 10,
            dotWidth: 10,
            dotColor: Colors.white,
            activeDotColor: MyColors.ORANGE_COLOR,
            spacing: 4.0, // Adjust spacing as needed
          ),
        ),
      ),
    ],
  );`**
![slide_dot_issue_right_side](https://github.com/Milad-Akarie/smooth_page_indicator/assets/7361686/a8cfad5b-a056-4b87-b67a-9ef68baf5947)

**Comment by Milad-Akarie** [comment]
@anilthummar for now if you have a big number of pages you properly should use a scrolling effect
