### ISSUE TITLE
Use indicator without controller

### ISSUE THREAD

**Issue by Prn-Ice** [Milad-Akarie/smooth_page_indicator#9]
The plugin takes a pageview controller as a required parameter, so I can't seem to use it with alternatives such as [carousel_slider](https://pub.dev/packages/carousel_slider), is there any way to use the two.

**Comment by Milad-Akarie** [comment]
@Prn-Ice  Implemented in `v0.2.0`.
use `AnimatedSmoothInidcator` widget instead of `SmoothPageIndicator`

**Comment by befirst** [comment]
not `AnimatedSmoothInidcator` but `AnimatedSmoothIndicator`
